### ISSUE TITLE
com.android.ui stopped working

### ISSUE THREAD

**Issue by lwndow** [ctbear/xposed-lockscreen-wallpaper#3]
Running on CM 11 M4, w/newest xposed + lockscreen wallpaper module + GNL, when my phone reboots, the UI stops working, crashes, the goes to modified lock screen, but the crash is jarring.

If there's any logs I can provide, please let me know. Also, apologies if this is the wrong place to file these!

**Comment by ctbear** [comment]
I have received a few reports about this, and it only happens on CM. My guess is CM had some system level changes that broke the routine of setting the wallpaper on the lockscreen at boot. This is not something I can fix.
If I feel like it down the road I might try to find a way around it. But since I haven't (and probably won't) used CM for such a long time this probably won't happen.

**Comment by lwndow** [comment]
Thanks for the quick reply!

**Comment by ghost** [comment]
I tried this mod on another Rom called P.A (based on AOSP not CM) but unfortunately I've the same bug as on CM.
Debug log : https://content.wuala.com/contents/Micks/Divers/Xposed_debug/xposed_debug_20140311_080130.zip/?dl=1
If you need tester please let me know.
Thanks.

**Comment by ctbear** [comment]
That does not look like AOSP to me. Do you have the source to it?

The problem with CM is on this line:
https://github.com/CyanogenMod/android_frameworks_base/blob/cm-11.0/packages/Keyguard/src/com/android/keyguard/KeyguardViewManager.java#L243

which I have no control over (meaning it's not broken because of something I do it). The log you uploaded suggests the same thing and looks nothing like the code from AOSP.

**Comment by ghost** [comment]
Yes sure, it isn't AOSP this is why I specify "based on" I don't have a Nexus device or Nexus Rom for my device but it's the Rom that you served for your mod (of course I disabled their own "see-through & frosted glass" feature for my test).
Link of source : https://github.com/AOSPA 
In fact this bug seems hit all Roms not AOSP which reduces significantly its compatibility, even if finally it works, the lock screen is changed.
And for CM maybe it's possible to bump this problem on their bug tracker but I don't know how their submit it...

**Comment by ctbear** [comment]
I figured it's paranoid when you mentioned PA. However I know for a fact PA doesn't change the part where you are having problem, and certainly will not crash the same way your log suggests.
If this affects other ROMs (especially AOSP based ones) I will need to find a way to fix it. If your ROM is truly AOSP based then I will need the source for it so I can at least try to see what can be broken. I'm less inclined to fix it if happens only on CM because I don't like the direction they are taking and it certainly is not a high impact/wide spread crash.

**Comment by ghost** [comment]
To be more clear my log comes from this Rom (AOSP, PA, both?): http://forum.xda-developers.com/galaxy-s2/orig-development/rom-paranoidandroid-4-0-beta-t2603784.
I can understand your view on CM, indeed it's really pity.
Anyway thanks for your time and have a nice day.
